In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data={"Jan":{"Battery":1,"Charger":8,"Pouch":4},"Feb":{"Battery":8,"Charger":2,"Pouch":7}}
data   # Nested dict say bhi hum data bana saktay hain DataFrame ka 

{'Jan': {'Battery': 1, 'Charger': 8, 'Pouch': 4},
 'Feb': {'Battery': 8, 'Charger': 2, 'Pouch': 7}}

In [4]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [5]:
data1=pd.DataFrame(data)   # is tarah hum dict k under dict say dataframe bana saktay hain
data1

Jan  Feb
Battery    1    8
Charger    8    2
Pouch      4    7

In [6]:
data1.T

Battery  Charger  Pouch
Jan        1        8      4
Feb        8        2      7

In [7]:
data1

Jan  Feb
Battery    1    8
Charger    8    2
Pouch      4    7

In [8]:
data2=pd.DataFrame(data1,index=["Clip","Battery","Charger","Pouch","Data Cable"])
data2

Jan  Feb
Clip        NaN  NaN
Battery     1.0  8.0
Charger     8.0  2.0
Pouch       4.0  7.0
Data Cable  NaN  NaN

In [9]:
data1

Jan  Feb
Battery    1    8
Charger    8    2
Pouch      4    7

In [10]:
pd.DataFrame(data1,index=["Clip","Battery","Charger","Pouch","Data Cable"])
data1

Jan  Feb
Battery    1    8
Charger    8    2
Pouch      4    7

In [11]:
data3={"Jan":data1["Jan"][0:1],"Feb":data1["Feb"][1:3]}  # is tarah hum aik new variable may poranay variable ka kuch 
data3                                                    #data slicing ki madad say utha saktay hain baqi ko wo NaN day ga

{'Jan': Battery    1
 Name: Jan, dtype: int64, 'Feb': Charger    2
 Pouch      7
 Name: Feb, dtype: int64}

In [12]:
pd.DataFrame(data3)

Jan  Feb
Battery  1.0  NaN
Charger  NaN  2.0
Pouch    NaN  7.0

In [13]:
data4=pd.DataFrame(data3)
data4

Jan  Feb
Battery  1.0  NaN
Charger  NaN  2.0
Pouch    NaN  7.0

In [14]:
data4.index.name="ITEM";data4.columns.name="MONTH"  # Is tariqay say hum Raw aur columns ka nname day saktay hain
data4

MONTH    Jan  Feb
ITEM             
Battery  1.0  NaN
Charger  NaN  2.0
Pouch    NaN  7.0

In [15]:
data4.values   # Values daykhnay ka tareqa

array([[ 1., nan],
       [nan,  2.],
       [nan,  7.]])

In [16]:
data4.index   # index daykhnay ka tareqa

Index(['Battery', 'Charger', 'Pouch'], dtype='object', name='ITEM')

In [17]:
data6=pd.Series(range(5),index=["a","b","c","d","e"])
data6

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [18]:
index=data6.index
index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [19]:
data6.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
data6.index[0:3]  # index ki slicing ka tariqa

Index(['a', 'b', 'c'], dtype='object')

In [21]:
data6.index[2:] 

Index(['c', 'd', 'e'], dtype='object')

In [22]:
data6.values

array([0, 1, 2, 3, 4], dtype=int64)

In [23]:
data6.values[3:]  # Values ki slicing ka tariqa

array([3, 4], dtype=int64)

In [24]:
index[1]=h   #index label modifies nhi ho sakta haan pora new index kar saktay hain

NameError: name 'h' is not defined

In [28]:
hassan=pd.Index(np.arange(5))
hassan

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [29]:
hussain=data6.index
hussain

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [30]:
data7=pd.Series([2,5,8,7,6],index=hussain) # is tara h bilqul eqaul quantity ka index hum ay saktay hain, Equal Qty must hay
data7

a    2
b    5
c    8
d    7
e    6
dtype: int64

In [31]:
data7.index is hussain # is tareqay say hum cross chk kar saktay hain k kia is Series may hussain jo hay wo index bana hay?

True

In [32]:
data7.index is hassan

False

In [33]:
data4.columns

Index(['Jan', 'Feb'], dtype='object', name='MONTH')

In [34]:
"Jan" in data4.columns  # is tareqay say hum DataFrame may chk kar saktay hain k kia yay value is column may hay?

True

In [35]:
"Battery" in data4.index  ## is tareqay say hum DataFrame may chk kar saktay hain k kia yay value is index  may hay?

True

In [36]:
"Keypad" in data4.index

False

In [37]:
data4

MONTH    Jan  Feb
ITEM             
Battery  1.0  NaN
Charger  NaN  2.0
Pouch    NaN  7.0

In [38]:
data8=pd.DataFrame(data4,index=["Cable","Cable","Pouch"])  # hum index ka naam same bhi rakh saktay hain
data8

MONTH  Jan  Feb
Cable  NaN  NaN
Cable  NaN  NaN
Pouch  NaN  7.0