In [1]:
names=['ali','hamza','saad']

In [3]:
for i in range(2):
    names.append(input('Enter your name'))

Enter your nameirfan
Enter your namejavaid


In [4]:
for name in names:
    print(name)

ali
hamza
saad
irfan
javaid


In [10]:
school_fee= [[50000,25000,30000],[15000,20000,25000]]

In [11]:
country_temps= [[[42,40,38]]]

In [12]:
import numpy as np

In [13]:
np.array([[[42,40,38]]])

array([[[42, 40, 38]]])

In [14]:
import pandas as pd

In [15]:
khi_temps= pd.Series([32,24,15,10,25])

In [16]:
khi_temps

0    32
1    24
2    15
3    10
4    25
dtype: int64

In [17]:
khi_temps.values

array([32, 24, 15, 10, 25], dtype=int64)

In [18]:
khi_temps.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
khi_temps= pd.Series([32,24,15,10,25,32,52,45,21,20])

In [20]:
khi_temps[khi_temps>35]

6    52
7    45
dtype: int64

In [21]:
khi_temps.index

RangeIndex(start=0, stop=10, step=1)

In [22]:
khi_temps[2]

15

In [23]:
khi_temps[2] = 35

In [24]:
khi_temps

0    32
1    24
2    35
3    10
4    25
5    32
6    52
7    45
8    21
9    20
dtype: int64

In [25]:
khi_temps[[2,3,4]]

2    35
3    10
4    25
dtype: int64

In [26]:
khi_temps[[4,2,3]]

4    25
2    35
3    10
dtype: int64

In [27]:
khi_temps[1:3]

1    24
2    35
dtype: int64

In [28]:
khi_temps **2

0    1024
1     576
2    1225
3     100
4     625
5    1024
6    2704
7    2025
8     441
9     400
dtype: int64

In [29]:
khi_temp_dict = {'10:00':35,'11:00':36,'12:00':38,'13:00':40}

In [30]:
khi_temps= pd.Series(khi_temp_dict)

In [31]:
khi_temps

10:00    35
11:00    36
12:00    38
13:00    40
dtype: int64

In [32]:
khi_temps.index

Index(['10:00', '11:00', '12:00', '13:00'], dtype='object')

In [33]:
khi_temps.values

array([35, 36, 38, 40], dtype=int64)

In [34]:
import pandas as pd

In [35]:
khi_temp_dict = {'10:00':35,'11:00':36,'12:00':38,'13:00':40}

In [36]:
khi_temps= pd.Series(khi_temp_dict,
                     index=['10:00','11:00','12:00','13:00','14:00'])

In [37]:
khi_temps

10:00    35.0
11:00    36.0
12:00    38.0
13:00    40.0
14:00     NaN
dtype: float64

In [38]:
pd.isnull(khi_temps)

10:00    False
11:00    False
12:00    False
13:00    False
14:00     True
dtype: bool

In [39]:
khi_temps.isnull()

10:00    False
11:00    False
12:00    False
13:00    False
14:00     True
dtype: bool

In [50]:
#pip install jupyterthemes

In [51]:
#pip install jupyterthemes

In [42]:
khi_temps

10:00    35.0
11:00    36.0
12:00    38.0
13:00    40.0
14:00     NaN
dtype: float64

In [43]:
lhr_temps_dict = {'10:00':30,'11:00':46,'12:00':28,'13:00':30,'09:00':25}

In [44]:
lhr_temps=pd.Series(lhr_temps_dict)

In [45]:
lhr_temps

10:00    30
11:00    46
12:00    28
13:00    30
09:00    25
dtype: int64

In [46]:
khi_temps + lhr_temps

09:00     NaN
10:00    65.0
11:00    82.0
12:00    66.0
13:00    70.0
14:00     NaN
dtype: float64

In [47]:
khi_temps.name='khi_temperature_data'

In [48]:
khi_temps

10:00    35.0
11:00    36.0
12:00    38.0
13:00    40.0
14:00     NaN
Name: khi_temperature_data, dtype: float64

In [52]:
khi_temps.index.name='khi_time'

In [53]:
khi_temps

khi_time
10:00    35.0
11:00    36.0
12:00    38.0
13:00    40.0
14:00     NaN
Name: khi_temperature_data, dtype: float64

In [54]:
students = pd.DataFrame([{'name':'fayyaz','age':26},{'name':'Meera','age':16},{'name':'sadiq','age':22}])

In [55]:
students

age    name
0   26  fayyaz
1   16   Meera
2   22   sadiq

In [56]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [57]:
frame = pd.DataFrame(data)

In [58]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [59]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [60]:
frame.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [61]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
....: index=['one', 'two', 'three', 'four',
....: 'five', 'six'])

In [62]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [63]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [64]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [65]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [66]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [67]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [68]:
frame2.loc[['one','two','three']]

year state  pop debt
one    2000  Ohio  1.5  NaN
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [69]:
frame2.loc['one':'three']

year state  pop debt
one    2000  Ohio  1.5  NaN
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [70]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [71]:
frame2['debt'] = 16.5

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [73]:
frame2['debt']

one      16.5
two      16.5
three    16.5
four     16.5
five     16.5
six      16.5
Name: debt, dtype: float64

In [74]:
val = pd.Series([-1.2, -1.5, -1.7,5.0], index=['two', 'four', 'five','seven'])


In [75]:
val

two     -1.2
four    -1.5
five    -1.7
seven    5.0
dtype: float64

In [76]:
frame2['debt'] = val


In [77]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [78]:
frame2.debt = 16.5

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [80]:
frame2.debt = val

In [81]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [82]:
frame2['income'] = 10.5

In [83]:
frame2

year   state  pop  debt  income
one    2000    Ohio  1.5   NaN    10.5
two    2001    Ohio  1.7  -1.2    10.5
three  2002    Ohio  3.6   NaN    10.5
four   2001  Nevada  2.4  -1.5    10.5
five   2002  Nevada  2.9  -1.7    10.5
six    2003  Nevada  3.2   NaN    10.5

In [84]:
frame2.income = 111

In [85]:
frame2

year   state  pop  debt  income
one    2000    Ohio  1.5   NaN     111
two    2001    Ohio  1.7  -1.2     111
three  2002    Ohio  3.6   NaN     111
four   2001  Nevada  2.4  -1.5     111
five   2002  Nevada  2.9  -1.7     111
six    2003  Nevada  3.2   NaN     111

In [86]:
frame2['eastern'] = frame2.state == 'Ohio'

In [87]:
frame2

year   state  pop  debt  income  eastern
one    2000    Ohio  1.5   NaN     111     True
two    2001    Ohio  1.7  -1.2     111     True
three  2002    Ohio  3.6   NaN     111     True
four   2001  Nevada  2.4  -1.5     111    False
five   2002  Nevada  2.9  -1.7     111    False
six    2003  Nevada  3.2   NaN     111    False

In [88]:
del frame2['eastern']

In [89]:
frame2

year   state  pop  debt  income
one    2000    Ohio  1.5   NaN     111
two    2001    Ohio  1.7  -1.2     111
three  2002    Ohio  3.6   NaN     111
four   2001  Nevada  2.4  -1.5     111
five   2002  Nevada  2.9  -1.7     111
six    2003  Nevada  3.2   NaN     111

In [90]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....: 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [91]:
frame3 = pd.DataFrame(pop)

In [92]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [93]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64')

In [94]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [95]:
distance=(20,50)

In [96]:
distance[0]

20

In [97]:
distance[0] = 30

TypeError: 'tuple' object does not support item assignment

In [ ]:
distance = (10,20,30,40)

In [ ]:
distance

In [98]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [99]:
obj

a    0
b    1
c    2
dtype: int64

In [100]:
obj.index 

Index(['a', 'b', 'c'], dtype='object')

In [101]:
obj.index[0]

'a'

In [102]:
obj.index[0] = 'k'

TypeError: Index does not support mutable operations

In [103]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [104]:
obj.index = ['k','l','j']

In [105]:
obj.index

Index(['k', 'l', 'j'], dtype='object')

In [106]:
obj

k    0
l    1
j    2
dtype: int64

In [107]:
obj.index = ['k','k','j']

In [108]:
obj

k    0
k    1
j    2
dtype: int64

In [109]:
obj.index

Index(['k', 'k', 'j'], dtype='object')

In [110]:
obj.loc['k']

k    0
k    1
dtype: int64

In [111]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [112]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [113]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [114]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [115]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [116]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [117]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [118]:
obj3.reindex(range(6),method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [119]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [120]:
frame2

year   state  pop  debt  income
one    2000    Ohio  1.5   NaN     111
two    2001    Ohio  1.7  -1.2     111
three  2002    Ohio  3.6   NaN     111
four   2001  Nevada  2.4  -1.5     111
five   2002  Nevada  2.9  -1.7     111
six    2003  Nevada  3.2   NaN     111

In [121]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [122]:
frame.index=['a','b','c','d','e','f']

In [123]:
frame


state  year  pop
a    Ohio  2000  1.5
b    Ohio  2001  1.7
c    Ohio  2002  3.6
d  Nevada  2001  2.4
e  Nevada  2002  2.9
f  Nevada  2003  3.2

In [124]:
frame.loc[['b','c'],['year','pop']]

year  pop
b  2001  1.7
c  2002  3.6

In [125]:
frame.iloc[0]

state    Ohio
year     2000
pop       1.5
Name: a, dtype: object